-- Magnitude Analysis

-- Find total customers by countires
Select country, COUNT(customer_number) as total_customers from GOLD.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
Select gender, COUNT(customer_number) as total_customers from gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by categories
Select category, COUNT(product_number) AS total_products from gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average cost in each categories
Select category, AVG(cost) AS average_cost from gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- Total revenue generated for each category
Select p.category, SUM(s.sales_amount) as total_revenue from gold.fact_sales s
LEFT JOIN gold.dim_products p 
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- What is the total revenue generated by each customer
SELECT c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) as total_revenue
from GOLD.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP by c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

-- what is the distribution of sold items across countries
SELECT	c.country, SUM(f.quantity) as total_items
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_items DESC
